# Datasets, Dataloaders

## Custom Dataset

In [5]:
import torch
from torch.utils.data import Dataset
from torch.utils.data import DataLoader

### Map Style Datasets

In [6]:
# Have to implement the __getitem__ function and potentially the __len__() function
# Inherits from Dataset

class CustomMapDataset(Dataset):
    def __init__(self, max_num):
        self._nums = list(range(0, max_num))
        
    def __len__(self):
        return len(self._nums)
    
    def __getitem__(self, index):
        return self._nums[index]

In [18]:
dataset = CustomMapDataset(5)

In [19]:
# you can access individual elements
print(dataset[0])
print(dataset[4])

0
4


In [20]:
#you can access the lenght of the dataset
len(dataset)

5

In [21]:
# and you can iterate throuth the dataset
for data in dataset:
    print(data)

0
1
2
3
4


## DataLoader

In [34]:
dataset = CustomMapDataset(100)
dataloader = DataLoader(dataset=dataset, batch_size=32, shuffle=True)

In [35]:
for data in dataloader:
    print(data)

tensor([63, 13, 15, 10, 24,  4, 50, 36, 57, 78,  6,  8, 51, 65, 48, 86, 23, 77,
         3, 94,  7, 81, 93, 26, 30, 27, 47, 99, 40, 44, 67,  9])
tensor([73, 87, 95, 97, 91, 89, 41,  1,  2, 33, 80, 68, 11,  0, 20, 42, 60, 83,
        84, 25, 69, 92, 37, 88, 71, 21, 55, 39, 49, 96, 28, 53])
tensor([43, 82, 75, 22, 64, 85, 70, 38, 61, 98, 72, 56, 90, 32, 58, 59, 17, 46,
        19, 34, 45, 18, 54, 29, 62, 52, 31, 14, 66, 12,  5, 35])
tensor([76, 16, 74, 79])
