In [2]:
import torch
import numpy as np

# Tensor Creation in PyTorch

## Setting the device to cuda or cpu

In [3]:
device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')

In [4]:
print(device)

cpu


## Create tensors

### torch.tensor()

In [5]:
t = torch.tensor([[1., 2.], [3., 4.]], device=device, dtype=torch.float32, requires_grad=True)

In [6]:
print(t)

tensor([[1., 2.],
        [3., 4.]], requires_grad=True)


In [7]:
t.dtype

torch.float32

In [8]:
t.shape

torch.Size([2, 2])

In [9]:
t.size()

torch.Size([2, 2])

In [10]:
t.requires_grad

True

### torch.ones()

In [17]:
t = torch.ones(2, 2)

In [20]:
t = torch.ones(size=(2, 2))

In [21]:
t

tensor([[1., 1.],
        [1., 1.]])

### torch.zeros()

In [22]:
t = torch.zeros(3, 3)

In [23]:
t

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

### from_numpy()

In [36]:
a = np.array([[2.0, 1.0], [3.0, 2.0]], dtype=np.float32)

In [37]:
t = torch.from_numpy(a) # tensor and array share the same memory

### torch.arange()

In [39]:
t = torch.arange(1, 10)

In [40]:
t

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

### torch.linspace()

In [47]:
t = torch.linspace(1, 10, 20)

In [46]:
t

tensor([ 1.0000,  1.4500,  1.9000,  2.3500,  2.8000,  3.2500,  3.7000,  4.1500,
         4.6000,  5.0500,  5.5000,  5.9500,  6.4000,  6.8500,  7.3000,  7.7500,
         8.2000,  8.6500,  9.1000,  9.5500, 10.0000])

### torch.logspace()

In [48]:
t = torch.logspace(1, 10, 20)

In [49]:
t

tensor([1.0000e+01, 2.9764e+01, 8.8587e+01, 2.6367e+02, 7.8476e+02, 2.3357e+03,
        6.9519e+03, 2.0691e+04, 6.1585e+04, 1.8330e+05, 5.4556e+05, 1.6238e+06,
        4.8329e+06, 1.4384e+07, 4.2813e+07, 1.2743e+08, 3.7927e+08, 1.1288e+09,
        3.3598e+09, 1.0000e+10])

### torch.eye()

In [50]:
t = torch.eye(5)

In [51]:
t

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

### torch.empty()

In [52]:
t = torch.empty(size=(3, 3))

In [53]:
t

tensor([[0.0000e+00, 0.0000e+00, 7.7052e+31],
        [7.2148e+22, 2.5226e-18, 2.5930e-09],
        [1.0186e-11, 3.0878e-09, 1.7188e-04]])

### torch.full()

In [55]:
t = torch.full(size=(2, 2), fill_value=3)

In [56]:
t

tensor([[3, 3],
        [3, 3]])

### torch.rand() - numbers from range [0, 1)

In [4]:
torch.rand(2,2)

tensor([[0.3498, 0.6212],
        [0.1384, 0.3782]])

### torch.randn() - standard normal dist

In [5]:
torch.randn(2,2)

tensor([[-0.6662, -0.1211],
        [ 0.6124,  2.1823]])

### torch.randint()

In [6]:
torch.randint(1, 5, (2, 2))

tensor([[1, 2],
        [3, 2]])