# PyTorch Slicing, Joining, Mutating

In [1]:
import torch

### Indexing

In [31]:
t = torch.tensor([1, 2, 3, 4, 5, 6, 7, 8])
t[1:5]

tensor([2, 3, 4, 5])

### torch.cat()

#### Concatenation only works along an existing axis

In [7]:
x = torch.tensor([1, 2, 3])
y = torch.tensor([4, 5, 6])

torch.cat((x, y), dim=0)

tensor([1, 2, 3, 4, 5, 6])

In [60]:
x = torch.tensor([[1, 2], [3, 4]])
y = torch.tensor([[5, 6], [7, 8]])

In [11]:
t1 = torch.cat((x, y), dim=0)
t1

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])

In [13]:
t2 = torch.cat((x, y), dim=1)
t2

tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])

### torch.gather()

In [20]:
# gather values 
t = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
torch.gather(t, 1, torch.tensor([[0], [1], [2]]))

tensor([[1],
        [5],
        [9]])

### torch.squeeze() and torch.unsqueeze()

In [21]:
t = torch.tensor([1, 2, 3])
t.shape

torch.Size([3])

In [25]:
#add a new dimension
t1 = t.unsqueeze(dim=0)
t1.shape

torch.Size([1, 3])

In [29]:
# remove a new dimension
t2 = t1.squeeze(dim=0)
t2.shape

torch.Size([3])

### view

In [32]:
t = torch.tensor([1, 2, 3, 4])
t.view((2, 2))

tensor([[1, 2],
        [3, 4]])

### torch.split()

In [33]:
t = torch.tensor([[1, 2], [3, 4], [5, 6], [7, 8]])

In [40]:
first, second = torch.split(t, 2)

In [41]:
first

tensor([[1, 2],
        [3, 4]])

In [42]:
second

tensor([[5, 6],
        [7, 8]])

### stack, dstack, vstack, hstack

In [47]:
#stack concatenates along a new dimension
t1 = torch.tensor([1, 2, 3])
t2 = torch.tensor([4, 5, 6])

In [48]:
torch.stack((t1, t2), dim=0)

tensor([[1, 2, 3],
        [4, 5, 6]])

In [49]:
torch.stack((t1, t2), dim=1)

tensor([[1, 4],
        [2, 5],
        [3, 6]])

### torch.t()

In [53]:
# transposes the 0 and 1 dimension
t = torch.tensor([[1,2,3], [4,5,6]])
torch.t(t)

tensor([[1, 4],
        [2, 5],
        [3, 6]])

### torch.transpose()

In [54]:
t = torch.rand(2, 3, 1)

In [59]:
torch.transpose(t, 2, 1)

tensor([[[0.5791, 0.0349, 0.9415]],

        [[0.9032, 0.5931, 0.7907]]])

### torch.unbind()

In [62]:
torch.unbind(torch.tensor([[1,2,3], [4,5,6], [7,8,9]]), dim=1)

(tensor([1, 4, 7]), tensor([2, 5, 8]), tensor([3, 6, 9]))