# Math Operations

In [1]:
import torch

In [2]:
t1 = torch.tensor([[1, 2], [3, 4]])
t2 = torch.tensor([[2, 3], [4, 5]])

## Addition/Subtraction/Division/Multiplication

In [3]:
t1+t2

tensor([[3, 5],
        [7, 9]])

In [4]:
t1.add(t2)

tensor([[3, 5],
        [7, 9]])

In [5]:
t1

tensor([[1, 2],
        [3, 4]])

In [6]:
# inplace operation
t1.add_(t2)

tensor([[3, 5],
        [7, 9]])

In [7]:
t1

tensor([[3, 5],
        [7, 9]])

In [8]:
t1-t2

tensor([[1, 2],
        [3, 4]])

In [9]:
t1/t2

tensor([[1.5000, 1.6667],
        [1.7500, 1.8000]])

In [10]:
t1*t2

tensor([[ 6, 15],
        [28, 45]])

## Broadcasting

In [12]:
t1 = torch.tensor([[1, 2, 3], [2, 3, 4]])
t2 = torch.tensor([2, 2, 2])
t1 + t2

tensor([[3, 4, 5],
        [4, 5, 6]])

## Special Operations

In [15]:
t = torch.tensor([1, 2, 3], dtype=torch.float32)
torch.exp(t)

tensor([ 2.7183,  7.3891, 20.0855])

## Reduction Operations

## argmax, argmin, amax, amin, max, min

In [20]:
# argmax, argmin return the index
# there is no dim option
t = torch.tensor([[3, 4, 1, 22, 9, 2, 5], [3, 4, 1, 22, 9, 2, 88]])
torch.argmax(t)

tensor(13)

In [23]:
# amax, amin return the max, min value. Dim option is available
t = torch.tensor([[3, 4, 1, 22, 9, 2, 5], [3, 4, 1, 22, 9, 2, 88]])
torch.amax(t, dim=1)

tensor([22, 88])

In [24]:
# max, min return both indices and values
t = torch.tensor([[3, 4, 1, 22, 9, 2, 5], [3, 4, 1, 22, 9, 2, 88]])
torch.max(t, dim=1)

torch.return_types.max(
values=tensor([22, 88]),
indices=tensor([3, 6]))

### mean, median, mode

In [26]:
t = torch.tensor([1, 2, 3, 4, 5], dtype=torch.float32)
t.mean()

tensor(3.)

### sum, prod

In [27]:
t = torch.tensor([1, 2, 3, 4, 5], dtype=torch.float32)

In [28]:
t.sum()

tensor(15.)

In [29]:
t.prod()

tensor(120.)

## Comparison operators

In [30]:
t1 = torch.tensor([[1, 2,], [2, 3]])
t2 = torch.tensor([[1, 3,], [2, 1]])
torch.eq(t1, t2)

tensor([[ True, False],
        [ True, False]])

In [31]:
#greater or equal
t1.ge(t2)

tensor([[ True, False],
        [ True,  True]])

In [32]:
t1.le(t2)

tensor([[ True,  True],
        [ True, False]])

In [33]:
# greater than
t1.gt(t2)

tensor([[False, False],
        [False,  True]])

In [34]:
t2.lt(t1)

tensor([[False, False],
        [False,  True]])